using SDL;

namespace WingCommander.Host.Sdl;

/// <summary>
/// Maps SDL scancodes to the IBM PC XT set-1 scan codes the game logic uses
/// (e.g. 0x01 Esc, 0x1C Enter, 0x39 Space, 0x48 Up, 0x50 Down, 0x4B Left, 0x4D Right).
/// Extended keys (cursor block, right Ctrl/Alt) map to the same codes as their numeric
/// keypad / left-hand counterparts, exactly like the DOS BIOS reported them.
/// </summary>
/// <remarks>C: SdlTranslateScanCode (src/sdl/input.c).</remarks>
public static class ScanCodes
{
    public static int FromSdl(SDL_Scancode scancode) => scancode switch
    {
        SDL_Scancode.SDL_SCANCODE_ESCAPE => 0x01,
        SDL_Scancode.SDL_SCANCODE_1 => 0x02,
        SDL_Scancode.SDL_SCANCODE_2 => 0x03,
        SDL_Scancode.SDL_SCANCODE_3 => 0x04,
        SDL_Scancode.SDL_SCANCODE_4 => 0x05,
        SDL_Scancode.SDL_SCANCODE_5 => 0x06,
        SDL_Scancode.SDL_SCANCODE_6 => 0x07,
        SDL_Scancode.SDL_SCANCODE_7 => 0x08,
        SDL_Scancode.SDL_SCANCODE_8 => 0x09,
        SDL_Scancode.SDL_SCANCODE_9 => 0x0a,
        SDL_Scancode.SDL_SCANCODE_0 => 0x0b,
        SDL_Scancode.SDL_SCANCODE_MINUS => 0x0c,
        SDL_Scancode.SDL_SCANCODE_EQUALS => 0x0d,
        SDL_Scancode.SDL_SCANCODE_BACKSPACE => 0x0e,
        SDL_Scancode.SDL_SCANCODE_TAB => 0x0f,
        SDL_Scancode.SDL_SCANCODE_Q => 0x10,
        SDL_Scancode.SDL_SCANCODE_W => 0x11,
        SDL_Scancode.SDL_SCANCODE_E => 0x12,
        SDL_Scancode.SDL_SCANCODE_R => 0x13,
        SDL_Scancode.SDL_SCANCODE_T => 0x14,
        SDL_Scancode.SDL_SCANCODE_Y => 0x15,
        SDL_Scancode.SDL_SCANCODE_U => 0x16,
        SDL_Scancode.SDL_SCANCODE_I => 0x17,
        SDL_Scancode.SDL_SCANCODE_O => 0x18,
        SDL_Scancode.SDL_SCANCODE_P => 0x19,
        SDL_Scancode.SDL_SCANCODE_LEFTBRACKET => 0x1a,
        SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET => 0x1b,
        SDL_Scancode.SDL_SCANCODE_RETURN => 0x1c,
        SDL_Scancode.SDL_SCANCODE_KP_ENTER => 0x1c,
        SDL_Scancode.SDL_SCANCODE_LCTRL => 0x1d,
        SDL_Scancode.SDL_SCANCODE_RCTRL => 0x1d,
        SDL_Scancode.SDL_SCANCODE_A => 0x1e,
        SDL_Scancode.SDL_SCANCODE_S => 0x1f,
        SDL_Scancode.SDL_SCANCODE_D => 0x20,
        SDL_Scancode.SDL_SCANCODE_F => 0x21,
        SDL_Scancode.SDL_SCANCODE_G => 0x22,
        SDL_Scancode.SDL_SCANCODE_H => 0x23,
        SDL_Scancode.SDL_SCANCODE_J => 0x24,
        SDL_Scancode.SDL_SCANCODE_K => 0x25,
        SDL_Scancode.SDL_SCANCODE_L => 0x26,
        SDL_Scancode.SDL_SCANCODE_SEMICOLON => 0x27,
        SDL_Scancode.SDL_SCANCODE_APOSTROPHE => 0x28,
        SDL_Scancode.SDL_SCANCODE_GRAVE => 0x29,
        SDL_Scancode.SDL_SCANCODE_LSHIFT => 0x2a,
        SDL_Scancode.SDL_SCANCODE_BACKSLASH => 0x2b,
        SDL_Scancode.SDL_SCANCODE_Z => 0x2c,
        SDL_Scancode.SDL_SCANCODE_X => 0x2d,
        SDL_Scancode.SDL_SCANCODE_C => 0x2e,
        SDL_Scancode.SDL_SCANCODE_V => 0x2f,
        SDL_Scancode.SDL_SCANCODE_B => 0x30,
        SDL_Scancode.SDL_SCANCODE_N => 0x31,
        SDL_Scancode.SDL_SCANCODE_M => 0x32,
        SDL_Scancode.SDL_SCANCODE_COMMA => 0x33,
        SDL_Scancode.SDL_SCANCODE_PERIOD => 0x34,
        SDL_Scancode.SDL_SCANCODE_SLASH => 0x35,
        SDL_Scancode.SDL_SCANCODE_KP_DIVIDE => 0x35,
        SDL_Scancode.SDL_SCANCODE_RSHIFT => 0x36,
        SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY => 0x37,
        SDL_Scancode.SDL_SCANCODE_PRINTSCREEN => 0x37,
        SDL_Scancode.SDL_SCANCODE_LALT => 0x38,
        SDL_Scancode.SDL_SCANCODE_RALT => 0x38,
        SDL_Scancode.SDL_SCANCODE_SPACE => 0x39,
        SDL_Scancode.SDL_SCANCODE_CAPSLOCK => 0x3a,
        SDL_Scancode.SDL_SCANCODE_F1 => 0x3b,
        SDL_Scancode.SDL_SCANCODE_F2 => 0x3c,
        SDL_Scancode.SDL_SCANCODE_F3 => 0x3d,
        SDL_Scancode.SDL_SCANCODE_F4 => 0x3e,
        SDL_Scancode.SDL_SCANCODE_F5 => 0x3f,
        SDL_Scancode.SDL_SCANCODE_F6 => 0x40,
        SDL_Scancode.SDL_SCANCODE_F7 => 0x41,
        SDL_Scancode.SDL_SCANCODE_F8 => 0x42,
        SDL_Scancode.SDL_SCANCODE_F9 => 0x43,
        SDL_Scancode.SDL_SCANCODE_F10 => 0x44,
        SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR => 0x45,
        SDL_Scancode.SDL_SCANCODE_SCROLLLOCK => 0x46,
        SDL_Scancode.SDL_SCANCODE_KP_7 => 0x47,
        SDL_Scancode.SDL_SCANCODE_HOME => 0x47,
        SDL_Scancode.SDL_SCANCODE_KP_8 => 0x48,
        SDL_Scancode.SDL_SCANCODE_UP => 0x48,
        SDL_Scancode.SDL_SCANCODE_KP_9 => 0x49,
        SDL_Scancode.SDL_SCANCODE_PAGEUP => 0x49,
        SDL_Scancode.SDL_SCANCODE_KP_MINUS => 0x4a,
        SDL_Scancode.SDL_SCANCODE_KP_4 => 0x4b,
        SDL_Scancode.SDL_SCANCODE_LEFT => 0x4b,
        SDL_Scancode.SDL_SCANCODE_KP_5 => 0x4c,
        SDL_Scancode.SDL_SCANCODE_KP_6 => 0x4d,
        SDL_Scancode.SDL_SCANCODE_RIGHT => 0x4d,
        SDL_Scancode.SDL_SCANCODE_KP_PLUS => 0x4e,
        SDL_Scancode.SDL_SCANCODE_KP_1 => 0x4f,
        SDL_Scancode.SDL_SCANCODE_END => 0x4f,
        SDL_Scancode.SDL_SCANCODE_KP_2 => 0x50,
        SDL_Scancode.SDL_SCANCODE_DOWN => 0x50,
        SDL_Scancode.SDL_SCANCODE_KP_3 => 0x51,
        SDL_Scancode.SDL_SCANCODE_PAGEDOWN => 0x51,
        SDL_Scancode.SDL_SCANCODE_KP_0 => 0x52,
        SDL_Scancode.SDL_SCANCODE_INSERT => 0x52,
        SDL_Scancode.SDL_SCANCODE_KP_PERIOD => 0x53,
        SDL_Scancode.SDL_SCANCODE_DELETE => 0x53,
        SDL_Scancode.SDL_SCANCODE_F11 => 0x57,
        SDL_Scancode.SDL_SCANCODE_F12 => 0x58,
        _ => 0,
    };
}
