<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.SDL3-CS" Version="2026.1002.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WingCommander.Core\WingCommander.Core.csproj" />
  </ItemGroup>

</Project>
